import Link from "next/link";
import type { Lang } from "../content";
import { TradeEnquiryForm } from "./TradeEnquiryForm";

export function InternationalTradePage({ lang }: { lang: Lang }) {
  const fr = lang === "fr";
  const base = `/${lang}`;
  const products = fr ? ["Lentilles vertes", "Lentilles rouges", "Pois chiches", "Pois jaunes", "Pois verts", "Autres légumineuses et produits agricoles canadiens étudiés sur demande"] : ["Green lentils", "Red lentils", "Chickpeas", "Yellow peas", "Green peas", "Other Canadian pulses and agricultural commodities considered upon request"];
  const steps = fr ? [
    ["01", "Transmettre les besoins", "L’acheteur transmet ses besoins concernant le produit."],
    ["02", "Examiner la demande", "Demlog examine la quantité, les spécifications et la destination demandées."],
    ["03", "Évaluer les possibilités", "La disponibilité et les conditions commerciales sont évaluées avec les partenaires d’approvisionnement concernés."],
    ["04", "Coordonner la transaction", "Les parties coordonnent la transaction commerciale et les documents requis."],
  ] : [
    ["01", "Submit requirements", "The buyer submits the product requirements."],
    ["02", "Review the enquiry", "Demlog reviews the requested quantity, specifications and destination."],
    ["03", "Evaluate opportunities", "Availability and commercial terms are evaluated with relevant supply partners."],
    ["04", "Coordinate the transaction", "The parties coordinate the commercial transaction and required documentation."],
  ];
  const buyers = fr ? ["Importateurs commerciaux", "Transformateurs alimentaires", "Grossistes et distributeurs", "Acheteurs de produits de base", "Agents d’approvisionnement", "Détaillants établis", "Autres acheteurs commerciaux qualifiés"] : ["Commercial importers", "Food processors", "Wholesalers and distributors", "Commodity buyers", "Purchasing agents", "Established retailers", "Other qualified business buyers"];

  return <>
    <section className="page-hero"><p className="eyebrow">{fr ? "COMMERCE INTERNATIONAL" : "INTERNATIONAL TRADE"}</p><h1>{fr ? "Produits agricoles canadiens pour les marchés internationaux" : "Canadian Agricultural Commodities for International Markets"}</h1><p className="lede">{fr ? "Demlog Customs & Trade Inc. met en relation des acheteurs internationaux qualifiés avec des possibilités sélectionnées d’approvisionnement en produits agricoles canadiens. Nos activités commerciales portent actuellement sur les légumineuses et des produits connexes, sous réserve de la disponibilité, des spécifications, des conditions commerciales et des exigences du pays de destination." : "Demlog Customs & Trade Inc. connects qualified international buyers with selected Canadian agricultural commodity opportunities. Our trade activities currently focus on pulses and related products, subject to availability, specifications, commercial terms and destination requirements."}</p><div className="hero-actions"><a className="button primary" href="#trade-enquiry">{fr ? "Soumettre une demande commerciale" : "Submit a Trade Enquiry"}</a><a className="button secondary" href="tel:+15149620243">{fr ? "Discuter de vos besoins" : "Discuss Your Requirements"}</a></div></section>
    <section className="section two-col"><div><p className="eyebrow">{fr ? "PRODUITS SÉLECTIONNÉS" : "SELECTED PRODUCTS"}</p><h2>{fr ? "Produits sélectionnés" : "Selected Products"}</h2><ul className="check-list">{products.map(product => <li key={product}>{product}</li>)}</ul></div><div><p className="lede">{fr ? "La disponibilité, la qualité, l’année de récolte, l’emballage, la quantité minimale et les conditions commerciales doivent être confirmés pour chaque demande." : "Product availability, grade, crop year, packaging, minimum quantity and commercial terms must be confirmed for each enquiry."}</p><p>{fr ? "Les produits et les spécifications disponibles varient selon l’année de récolte, le fournisseur et la destination." : "Available products and specifications vary according to crop year, supplier and destination."}</p></div></section>
    <section className="section"><p className="eyebrow">{fr ? "MARCHÉS INTERNATIONAUX" : "INTERNATIONAL MARKETS"}</p><h2>{fr ? "Demandes provenant des marchés internationaux" : "International Market Enquiries"}</h2><p className="lede">{fr ? "Nous accueillons les demandes d’importateurs, de distributeurs, de transformateurs alimentaires, de grossistes et d’autres acheteurs commerciaux qualifiés partout dans le monde. Nos activités actuelles de développement de marchés comprennent notamment la Türkiye, la Colombie et d’autres destinations internationales sélectionnées." : "We welcome enquiries from established importers, distributors, food processors, wholesalers and other qualified commercial buyers worldwide. Our current market development activities include Türkiye, Colombia and other selected international destinations."}</p><p>{fr ? "Demlog accueille les demandes d’acheteurs qualifiés du monde entier, avec un intérêt actuel pour des marchés sélectionnés, notamment la Türkiye et la Colombie." : "Demlog welcomes enquiries from qualified buyers worldwide, with a current market focus that includes Türkiye, Colombia and other selected international markets."}</p></section>
    <section className="section process dark"><p className="eyebrow">{fr ? "FONCTIONNEMENT" : "HOW IT WORKS"}</p><h2>{fr ? "De la demande à une possibilité commerciale évaluée" : "From buyer requirements to an evaluated trade opportunity"}</h2><div className="card-grid">{steps.map(step => <article className="service-card" key={step[0]}><span>{step[0]}</span><h3>{step[1]}</h3><p>{step[2]}</p></article>)}</div></section>
    <section className="section split"><div><p className="eyebrow">{fr ? "DEUX ACTIVITÉS DISTINCTES" : "TWO DISTINCT ACTIVITIES"}</p><h2>{fr ? "Commerce et expertise douanière au sein d’une même entreprise" : "Trade and Customs Expertise Under One Company"}</h2><p>{fr ? "Les activités de commerce international sont distinctes des services canadiens de courtage en douane de Demlog. Lorsque des marchandises sont importées au Canada, Demlog peut fournir des services de dédouanement canadien lorsque cela est approprié. Les exportations vers des destinations étrangères demeurent assujetties aux exigences du pays de destination et peuvent nécessiter l’intervention de transporteurs, de transitaires, de sociétés d’inspection, d’institutions financières et de professionnels douaniers étrangers indépendants." : "International trade activities are separate from Demlog’s Canadian customs-brokerage services. When goods are imported into Canada, Demlog can provide Canadian customs-clearance support where appropriate. Exports to foreign destinations remain subject to the destination country’s requirements and may involve independent carriers, freight forwarders, inspection providers, banks and foreign customs professionals."}</p><Link className="text-link" href={`${base}/canadian-customs-clearance`}>{fr ? "Services de dédouanement canadien →" : "Canadian customs-clearance services →"}</Link></div><div><p className="eyebrow">{fr ? "ACHETEURS COMMERCIAUX" : "COMMERCIAL BUYERS"}</p><h2>{fr ? "Qui devrait communiquer avec Demlog" : "Who Should Contact Demlog"}</h2><ul className="check-list">{buyers.map(buyer => <li key={buyer}>{buyer}</li>)}</ul><p>{fr ? "Cette activité vise principalement les quantités commerciales et les demandes d’entreprises légitimes. Elle ne s’adresse pas aux achats individuels des consommateurs." : "This activity is intended primarily for commercial quantities and legitimate business enquiries. It is not intended for individual consumer purchases."}</p></div></section>
    <section className="section content" id="trade-enquiry"><p className="eyebrow">{fr ? "DEMANDE COMMERCIALE" : "TRADE ENQUIRY"}</p><h2>{fr ? "Présentez vos besoins commerciaux" : "Submit your commercial requirements"}</h2><p>{fr ? "Veuillez fournir suffisamment de détails pour permettre une première évaluation de la possibilité d’approvisionnement et des exigences de destination." : "Provide enough detail for an initial assessment of the supply opportunity and destination requirements."}</p><TradeEnquiryForm lang={lang} /><div className="notice"><strong>{fr ? "Avis commercial" : "Commercial disclaimer"}</strong><p>{fr ? "Tous les produits, quantités, spécifications, prix, conditions de livraison et modalités de transaction sont assujettis à la disponibilité, à la vérification diligente, à une entente contractuelle ainsi qu’aux exigences applicables au Canada et dans le pays de destination." : "All products, quantities, specifications, pricing, delivery terms and transaction arrangements are subject to availability, due diligence, contractual agreement and applicable Canadian and destination-country requirements."}</p></div></section>
  </>;
}
