export type Lang = "en" | "fr";

export const services = [
  ["canadian-customs-clearance", "Canadian Customs Clearance", "Dédouanement canadien", "Coordinated customs clearance for commercial goods entering Canada by highway, air, ocean or courier.", "Coordination du dédouanement des marchandises commerciales entrant au Canada par route, air, mer ou messagerie."],
  ["commercial-import-clearance", "Commercial Import Clearance", "Dédouanement des importations commerciales", "Release preparation, accounting support and practical guidance for routine commercial imports.", "Préparation de la mainlevée, soutien à la déclaration en détail et conseils pratiques pour les importations commerciales."],
  ["highway-truck-clearance", "Highway & Truck Clearance", "Dédouanement routier", "PARS-focused support for truck shipments before they reach the Canadian border.", "Soutien axé sur le PARS pour les expéditions routières avant leur arrivée à la frontière canadienne."],
  ["pars-clearance", "PARS Shipment Clearance", "Dédouanement PARS", "Review and transmission support for highway cargo control documents and shipment data.", "Révision et transmission des documents de contrôle du fret routier et des données d’expédition."],
  ["air-freight-clearance", "Air Freight Clearance", "Dédouanement du fret aérien", "Time-sensitive customs clearance support for commercial goods arriving by air.", "Soutien au dédouanement urgent des marchandises commerciales arrivant par voie aérienne."],
  ["ocean-freight-clearance", "Ocean Freight Clearance", "Dédouanement maritime", "Customs preparation for FCL and LCL commercial shipments arriving at Canadian ports.", "Préparation douanière des envois commerciaux FCL et LCL arrivant dans les ports canadiens."],
  ["courier-clearance", "Courier & Express Clearance", "Dédouanement messagerie et express", "Help when a commercial courier shipment requires formal customs handling or importer action.", "Aide lorsqu’un envoi commercial par messagerie exige un traitement douanier officiel ou une action de l’importateur."],
  ["regulated-goods", "OGD/PGA & Regulated Goods", "Marchandises réglementées et AM/OGP", "Support for admissible regulated goods subject to permits, licences and participating-government-agency requirements.", "Soutien pour les marchandises réglementées admissibles, sous réserve des permis, licences et exigences des autres ministères."],
  ["tariff-classification", "Tariff Classification & HS Codes", "Classement tarifaire et codes SH", "Classification research to identify the tariff item that best matches the goods and supporting facts.", "Recherche de classement pour déterminer le numéro tarifaire correspondant aux marchandises et aux faits justificatifs."],
  ["duties-taxes", "Duties & Taxes Guidance", "Droits et taxes à l’importation", "Plain-language guidance on tariff treatment, duty, GST and other import charges.", "Explications claires sur le traitement tarifaire, les droits, la TPS et les autres frais d’importation."],
  ["carm-rpp", "CARM, GCRA & RPP Assistance", "Aide GCRA et mainlevée avant paiement", "Help with CARM delegation, importer setup and Release Prior to Payment preparation.", "Aide pour la délégation dans la GCRA, l’inscription de l’importateur et la mainlevée avant paiement."],
  ["first-time-importers", "First-Time Importer Assistance", "Aide aux nouveaux importateurs", "A practical starting point for businesses importing commercial goods into Canada for the first time.", "Un point de départ pratique pour les entreprises qui importent des marchandises commerciales au Canada pour la première fois."],
  ["non-resident-importers", "Non-Resident Importer Assistance", "Aide aux importateurs non-résidents", "Planning support for foreign businesses considering non-resident importer arrangements in Canada.", "Soutien à la planification pour les entreprises étrangères envisageant le statut d’importateur non-résident au Canada."],
  ["trade-compliance", "Customs & Trade Compliance Consulting", "Conseil en conformité douanière", "Import-process reviews, documentation guidance and practical compliance support.", "Examen des processus d’importation, conseils documentaires et soutien pratique en conformité."],
  ["post-entry", "Corrections & Post-Entry Support", "Corrections et soutien après déclaration", "Assessment of corrections, adjustments and post-entry steps where supported by the available records.", "Évaluation des corrections, rajustements et démarches après déclaration selon les documents disponibles."],
] as const;

export const corePages = [
  ["services", "Customs Brokerage Services", "Services de courtage en douane", "Canadian customs clearance, classification, CARM and regulated-goods support.", "Dédouanement canadien, classement, GCRA et soutien aux marchandises réglementées."],
  ["about", "About Demlog", "À propos de Demlog", "Direct, independent Canadian customs brokerage built around responsive professional support.", "Un courtage en douane canadien indépendant axé sur un soutien professionnel et réactif."],
  ["contact", "Contact Demlog", "Communiquer avec Demlog", "Speak directly with a customs professional about an import, clearance request or compliance question.", "Discutez directement avec un professionnel des douanes d’une importation, d’une demande de dédouanement ou d’une question de conformité."],
  ["get-started", "Become a Demlog Client", "Devenir client de Demlog", "Start the onboarding conversation without sending sensitive customs documents through a public form.", "Commencez le processus sans transmettre de documents douaniers sensibles par un formulaire public."],
  ["request-clearance", "Request Customs Clearance", "Demander un dédouanement", "Tell us the essentials about your shipment. We will review the information and explain the next step.", "Transmettez-nous les renseignements essentiels. Nous les examinerons et expliquerons la prochaine étape."],
  ["pars-tracker", "Check a PARS or Transaction Number", "Vérifier un PARS ou un numéro de transaction", "Open the official Descartes status checker to review a PARS, PAPS, cargo control or transaction number.", "Ouvrez le vérificateur officiel Descartes pour consulter un PARS, PAPS, numéro de contrôle du fret ou numéro de transaction."],
  ["pricing", "$50 Flat-Rate Customs Clearance", "Dédouanement à tarif fixe de 50 $", "One professional customs-clearance fee with no accessorial charges for extra invoice lines, after-hours processing or OGD/PGA handling.", "Un seul tarif professionnel de dédouanement, sans frais accessoires pour les lignes de facture additionnelles, le traitement hors heures ou les exigences AM/OGP."],
  ["faq", "Frequently Asked Questions", "Questions fréquentes", "Clear answers about commercial importing, timing, documents, CARM and regulated goods.", "Réponses claires sur l’importation commerciale, les délais, les documents, la GCRA et les marchandises réglementées."],
  ["glossary", "Customs & Import Glossary", "Glossaire des douanes et de l’importation", "Plain-language definitions for common Canadian customs terms.", "Définitions simples des principaux termes douaniers canadiens."],
  ["resources", "Canadian Customs Resources & Import Guides", "Ressources douanières canadiennes et guides d’importation", "Practical customs articles, import checklists and authoritative Canadian sources for commercial importers.", "Articles douaniers, listes de vérification et sources canadiennes officielles pour les importateurs commerciaux."],
  ["industries", "Industries We Support", "Secteurs que nous soutenons", "Customs support adapted to the documents, agencies and risks that vary by product category.", "Soutien douanier adapté aux documents, organismes et risques propres aux différentes catégories de produits."],
  ["privacy", "Privacy Policy", "Politique de confidentialité", "Demlog collects contact and shipment-summary information to answer enquiries, provide requested services and protect its forms. Non-essential analytics and advertising technologies remain disabled until the required consent is obtained. Service providers may process information in Canada or other jurisdictions. Information is retained only as reasonably necessary, protected with administrative and technical safeguards, and may be accessed or corrected by contacting the Person Responsible for the Protection of Personal Information at berdan.demirel@demlogct.com. This draft should be reviewed by a Québec privacy professional before launch.", "Demlog recueille les coordonnées et un résumé de l’expédition pour répondre aux demandes, fournir les services demandés et protéger ses formulaires. Les outils d’analyse et de publicité non essentiels restent désactivés jusqu’à l’obtention du consentement requis. Des fournisseurs peuvent traiter des renseignements au Canada ou ailleurs. Les renseignements sont conservés seulement pendant la période raisonnablement nécessaire et protégés par des mesures administratives et techniques. Pour demander l’accès ou la rectification, communiquez avec la personne responsable de la protection des renseignements personnels à berdan.demirel@demlogct.com. Ce projet doit être révisé par un professionnel québécois avant le lancement."],
  ["terms", "Terms of Use", "Conditions d’utilisation", "By using this site, you agree to use its information lawfully and acknowledge that content may change. The website does not create a broker-client relationship until Demlog accepts an engagement. External links are provided for convenience.", "En utilisant ce site, vous acceptez d’utiliser les renseignements légalement et reconnaissez que le contenu peut changer. Le site ne crée pas une relation courtier-client avant l’acceptation d’un mandat par Demlog. Les liens externes sont fournis à titre pratique."],
  ["disclaimer", "Customs Services Disclaimer", "Avis relatif aux services douaniers", "Website content is general information, not legal, tax or binding classification advice. Customs release, admissibility, duties and agency approval depend on shipment facts and government decisions. Prohibited goods cannot be cleared; regulated goods may require permits or licences.", "Le contenu du site est général et ne constitue pas un avis juridique, fiscal ou un classement contraignant. La mainlevée, l’admissibilité, les droits et l’approbation dépendent des faits et des décisions gouvernementales. Les marchandises prohibées ne peuvent être dédouanées; les marchandises réglementées peuvent exiger des permis ou licences."],
  ["accessibility", "Accessibility Statement", "Déclaration d’accessibilité", "Demlog aims to meet WCAG 2.2 AA through semantic structure, keyboard access, visible focus, readable type, adequate contrast and reduced-motion support. Report a barrier to berdan.demirel@demlogct.com or +1 (514) 962-0243.", "Demlog vise les WCAG 2.2 AA grâce à une structure sémantique, l’accès au clavier, un focus visible, une typographie lisible, un contraste suffisant et la réduction des mouvements. Signalez un obstacle à berdan.demirel@demlogct.com ou au +1 514 962-0243."],
  ["sitemap", "Website Sitemap", "Plan du site", "Browse Demlog’s English and French pages, services and practical resources from the navigation and resource directories on this page.", "Parcourez les pages, services et ressources pratiques de Demlog en français et en anglais à partir de la navigation et des répertoires du site."],
] as const;

export const articles = [
  ["how-commercial-customs-clearance-works-canada", "How Commercial Customs Clearance Works in Canada", "Fonctionnement du dédouanement commercial au Canada"],
  ["documents-needed-import-commercial-goods-canada", "Documents Needed to Import Commercial Goods Into Canada", "Documents requis pour importer des marchandises commerciales au Canada"],
  ["understanding-pars-status-border-delays", "Understanding PARS Status and Common Border Delays", "Comprendre le statut PARS et les retards à la frontière"],
] as const;

export const futureArticles = [
  "How CARM affects Canadian importers", "How to appoint a customs broker in CARM", "What Release Prior to Payment means", "How Canadian import duties and GST are calculated", "How to find and verify an HS code", "Common reasons a shipment is held at the Canadian border", "Importing food and beverages into Canada", "Importing machinery into Canada", "Importing clothing and textiles into Canada", "Importer of record versus non-resident importer", "Switching customs brokers", "A first-time importer checklist", "What an OGD/PGA requirement means", "Air versus ocean versus highway clearance", "Information a customs broker needs before arrival"
];

export function findPage(slug: string, lang: Lang) {
  const service = services.find((p) => p[0] === slug);
  if (service) return { kind: "service", title: service[lang === "en" ? 1 : 2], description: service[lang === "en" ? 3 : 4] };
  const core = corePages.find((p) => p[0] === slug);
  if (core) return { kind: slug, title: core[lang === "en" ? 1 : 2], description: core[lang === "en" ? 3 : 4] };
  const article = articles.find((p) => p[0] === slug);
  if (article) return { kind: "article", title: article[lang === "en" ? 1 : 2], description: lang === "en" ? "A practical, plain-language guide for commercial importers." : "Un guide pratique et clair à l’intention des importateurs commerciaux." };
  return null;
}
